/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterSol from './Counter.sol/index.js';
export type { counterSol };
import type * as myNftSol from './MyNFT.sol/index.js';
export type { myNftSol };
export * as factories from './factories/index.js';
export type { Counter } from './Counter.sol/Counter.js';
export { Counter__factory } from './factories/Counter.sol/Counter__factory.js';
export type { MyNFT } from './MyNFT.sol/MyNFT.js';
export { MyNFT__factory } from './factories/MyNFT.sol/MyNFT__factory.js';